xeneta_cs:
  outputs:
    dev:
      type: duckdb
      path: 'C:/Users/ZZ00OL808/xeneta_cs/db/xeneta.duckdb'
      threads: 1

    prod:
      type: duckdb
      path: prod.duckdb
      threads: 4

  target: dev
